version: '3.8'

services:
  redis-cache:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    build: .
    container_name: test-task-app
    ports:
      - "8888:8888"
    depends_on:
      - redis-cache
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - app_data:/app/data
    networks:
      - app-network

volumes:
  app_data:

networks:
  app-network:
    driver: bridge